# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/M6 to M7 - Vanilla System/Nexys4_DDR_chu.xdc

# IP: ip/microblaze_mcs_0/microblaze_mcs_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_mcs_0 || ORIG_REF_NAME==microblaze_mcs_0} -quiet] -quiet

# Block Designs: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0 || ORIG_REF_NAME==bd_fc5c_0} -quiet] -quiet

# IP: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_microblaze_I_0 || ORIG_REF_NAME==bd_fc5c_0_microblaze_I_0} -quiet] -quiet

# IP: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_rst_0_0 || ORIG_REF_NAME==bd_fc5c_0_rst_0_0} -quiet] -quiet

# IP: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_2/bd_fc5c_0_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_ilmb_0 || ORIG_REF_NAME==bd_fc5c_0_ilmb_0} -quiet] -quiet

# IP: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_0_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_dlmb_0 || ORIG_REF_NAME==bd_fc5c_0_dlmb_0} -quiet] -quiet

# IP: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_4/bd_fc5c_0_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_dlmb_cntlr_0 || ORIG_REF_NAME==bd_fc5c_0_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_5/bd_fc5c_0_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_ilmb_cntlr_0 || ORIG_REF_NAME==bd_fc5c_0_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_0_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_lmb_bram_I_0 || ORIG_REF_NAME==bd_fc5c_0_lmb_bram_I_0} -quiet] -quiet

# IP: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_0_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_mdm_0_0 || ORIG_REF_NAME==bd_fc5c_0_mdm_0_0} -quiet] -quiet

# IP: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_8/bd_fc5c_0_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_xlconcat_0_0 || ORIG_REF_NAME==bd_fc5c_0_xlconcat_0_0} -quiet] -quiet

# IP: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_9/bd_fc5c_0_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fc5c_0_iomodule_0_0 || ORIG_REF_NAME==bd_fc5c_0_iomodule_0_0} -quiet] -quiet

# XDC: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_microblaze_I_0 || ORIG_REF_NAME==bd_fc5c_0_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0_ooc_debug.xdc

# XDC: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_rst_0_0 || ORIG_REF_NAME==bd_fc5c_0_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_rst_0_0 || ORIG_REF_NAME==bd_fc5c_0_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_0_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_dlmb_0 || ORIG_REF_NAME==bd_fc5c_0_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_0_lmb_bram_I_0_ooc.xdc

# XDC: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_0_mdm_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_mdm_0_0 || ORIG_REF_NAME==bd_fc5c_0_mdm_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_0_mdm_0_0_ooc_trace.xdc

# XDC: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_9/bd_fc5c_0_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_0_iomodule_0_0 || ORIG_REF_NAME==bd_fc5c_0_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c_0_ooc.xdc

# XDC: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_mcs_0 || ORIG_REF_NAME==microblaze_mcs_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/noah/Projects/ECE-4310_Lab-7v11/ECE-4310_Lab-7v11.gen/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_ooc.xdc
